export const GET_USERS_STARTED = 'USER/GET_USERS_STARTED';
export const GET_USERS_SUCCESS = 'USER/GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'USER/GET_USERS_FAILURE';

export const GET_USER_STARTED = 'USER/GET_USER_STARTED';
export const GET_USER_SUCCESS = 'USER/GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'USER/GET_USER_FAILURE';

export const CREATE_STARTED = 'USER/CREATE_STARTED';
export const CREATE_SUCCESS = 'USER/CREATE_SUCCESS';
export const CREATE_FAILURE = 'USER/CREATE_FAILURE';

export const UPDATE_STARTED = 'USER/UPDATE_STARTED';
export const UPDATE_SUCCESS = 'USER/UPDATE_SUCCESS';
export const UPDATE_FAILURE = 'USER/UPDATE_FAILURE';