export const FETCH_STARTED = 'USER/FETCH_STARTED';
export const FETCH_SUCCESS = 'USER/FETCH_SUCCESS';
export const FETCH_FAILURE = 'USER/FETCH_FAILURE';

export const CREATE_STARTED = 'USER/CREATE_STARTED';
export const CREATE_SUCCESS = 'USER/CREATE_SUCCESS';
export const CREATE_FAILURE = 'USER/CREATE_FAILURE';